services:
  backend:
    build:
      context: .
      target: builder
    depends_on:
      db:
        condition: service_healthy
    env_file: .env

  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}"
      - POSTGRES_USER=${DB_USER}"
      - POSTGRES_PASSWORD=${DB_PASSWORD}"
    ports:
      - ${DB_PORT}:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  proxy:
    image: nginx
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 80:80
    depends_on:
      - backend

volumes:
  db-data:


